package org.mongodb.meclipse;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

import org.eclipse.core.runtime.FileLocator;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import org.eclipse.core.runtime.Platform;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.jface.resource.ImageRegistry;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.mongodb.meclipse.preferences.MongoInstance;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;

/**
 * The activator class controls the plug-in life cycle
 * @author Flavio [FlaPer87] Percoco Premoli, walknwind
 */
public class MeclipsePlugin extends AbstractUIPlugin {

	// The plug-in ID
	public static final String PLUGIN_ID = "org.mongodb.meclipse";
	
	private HashMap<String, MongoInstance> mongoInstances = new HashMap<String, MongoInstance>();

	// The shared instance
	private static MeclipsePlugin plugin;
	
	/**
	 * The constructor
	 */
	public MeclipsePlugin() {
	}

	/*
	 * (non-Javadoc)
	 * @see org.eclipse.ui.plugin.AbstractUIPlugin#start(org.osgi.framework.BundleContext)
	 */
	public void start(BundleContext context) throws Exception {
		super.start(context);
		plugin = this;
		MongoInstance[] savedServers = loadSavedServers();
		for (MongoInstance savedServer : savedServers)
		{
			mongoInstances.put(savedServer.getName(), savedServer);
		}
	}

	/*
	 * (non-Javadoc)
	 * @see org.eclipse.ui.plugin.AbstractUIPlugin#stop(org.osgi.framework.BundleContext)
	 */
	public void stop(BundleContext context) throws Exception {
		plugin = null;
		saveServers();
		super.stop(context);
	}

	/**
	 * Returns the shared instance
	 *
	 * @return the shared instance
	 */
	public static MeclipsePlugin getDefault() {
		return plugin;
	}
	
	/**
	 * Taken from EclipseTracPlugin
	 * 
     * Returns an image descriptor for the image file at the given plug-in
     * relative path
     * 
     * @param path
     *            the path
     * @return the image descriptor
     */
    protected static ImageDescriptor getImageDescriptor( String path )
    {
        return imageDescriptorFromPlugin( PLUGIN_ID, path );
    }
    
	// IMAGE HANDLING
	public static final String COLLECTION_IMG_ID =	"./icons/table.png";
	public static final String CONNECTION_IMG_ID =	"./icons/leaf.png";
	public static final String DATABASE_IMG_ID =	"./icons/database.png";
	
	final List<String> IMG_ID_LIST =
		new ArrayList<String> ()
		{
			/**
			 * Generated by Eclipse
			 */
			private static final long serialVersionUID = 666142153396600669L;

			{
				add (COLLECTION_IMG_ID);
				add (CONNECTION_IMG_ID);
				add (DATABASE_IMG_ID);
			}
		};
		
		@Override
		protected void initializeImageRegistry(ImageRegistry registry)
		{
			super.initializeImageRegistry(registry);
			Bundle bundle = Platform.getBundle(PLUGIN_ID);
			for (String img_id : IMG_ID_LIST)
			{
				ImageDescriptor myImage = ImageDescriptor.createFromURL(
						FileLocator.find(bundle, new Path(img_id), null));
				registry.put(img_id, myImage);
			}
		}

		public void addMongo(String name, MongoInstance conn) {
			this.mongoInstances.put(name, conn);
		}
		
		public MongoInstance getMongoInstance(String name)
		{
			return mongoInstances.get(name);
		}

		public Set<String> getMongoNames() {
			return mongoInstances.keySet();
		}
		
		private MongoInstance[] loadSavedServers() {
			FileInputStream inputStream = null;
			try {
				IPath libPath = MeclipsePlugin.getDefault().getStateLocation();
				libPath = libPath.append("servers.cfg");
				File file = libPath.toFile();
				if (!file.exists())
					return new MongoInstance[0];
				
				inputStream = new FileInputStream(file);
				DataInputStream dataInputStream = new DataInputStream(inputStream);
				BufferedReader bReader = new BufferedReader(new InputStreamReader(dataInputStream));
				
				java.util.List<MongoInstance> savedServersList = new ArrayList<MongoInstance>();
				String line;
				while ((line = bReader.readLine()) != null)
				{
					// TODO: use CsvWriter
					String[] values = line.split(",");
					MongoInstance server = new MongoInstance(values[0]);
					server.setHost(values[1]);
					try
					{
						server.setPort(Integer.valueOf(values[2]));
					}
					catch (NumberFormatException ex)
					{
						System.out.println(ex);
					}
					savedServersList.add(server);
				}
				return savedServersList.toArray(new MongoInstance[savedServersList.size()]);
			}
			catch(IOException ex)
			{
				ex.printStackTrace();
			}
			return new MongoInstance[0];
		}
		
	private void saveServers()
	{
		// save server preferences here
		FileWriter writer = null;
		try {
			IPath libPath = getStateLocation();
			libPath = libPath.append("servers.cfg");
			File file = libPath.toFile();
			if (!file.exists())
				file.createNewFile();
			writer = new FileWriter(file, false); // overwrite all servers
			for (MongoInstance server : mongoInstances.values())
			{
				writer.write(server.getName() + "," + server.getHost() + "," + server.getPort() + "\n");
			}
		
		}
		/*
		catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		*/
		catch(IOException ex)
		{
			ex.printStackTrace();
		}
		finally
		{
			if (writer != null)
			{
				try
				{
					writer.close();
				}
				catch (IOException e1)
				{
					e1.printStackTrace();
				}
			}
		}// end finally
	}

	public void removeMongo(String name) {
		mongoInstances.remove(name);
	}
	
	public void markMongoDeleted(String name)
	{
		mongoInstances.get(name).setIsDeleted(true);		
	}
}
